# Generated by Django 4.0.4 on 2022-05-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('nights', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=100)),
            ],
        ),
    ]
